--- 
files: 
  -
    source: /*.jar
    destination: /usr/share/tomcat8/webapps

hooks:
  BeforeInstall:
      -
        location: deploy_hooks/stop-tomcat.sh
        runas: root
        timeout: 3600
  ApplicationStart:
    -
      location: deploy_hooks/start-tomcat.sh
      runas: root
      timeout: 3600
  ValidateService:
    - 
      location: deploy_hooks/validate-change.sh
      timeout: 3600
os: linux
version: 0.0
